baseurl = "https://code.makery.ch"
title = "code.makery.ch"
pluralizeListTitles = false
preserveTaxonomyNames = true
removePathAccents = true
enableRobotsTXT = true

disableFastRender = true

defaultContentLanguage = "en"

[params]
  intro = "Learning how to code."
  author = "Marco Jakob"
  email = "info@makery.ch"
  analyticsId = "UA-34917397-3"
  disqusShortname = "codemakery"
  twitter = "codemakery"
  github = "https://github.com/marcojakob/code.makery.ch"

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  topic = "topics"
  tag = "tags"

[permalinks]
  topics = "/library/topic/:slug/"
  tags = "/blog/tag/:slug/"

[languages]
[languages.en]
  languageName = "English"
  weight = 1

[languages.de]
  languageName = "Deutsch"
  weight = 2

[languages.es]
  languageName = "Español"
  weight = 3

[languages.fa]
  languageName = "فارسی"
  weight = 4

[languages.fr]
  languageName = "Français"
  weight = 5

[languages.id]
  languageName = "Bahasa Indonesia"
  weight = 6

[languages.it]
  languageName = "Italiano"
  weight = 7

[languages.kr]
  languageName = "한국어"
  weight = 8

[languages.pt]
  languageName = "Português"
  weight = 9

[languages.ru]
  languageName = "Русский"
  weight = 10

[languages.uk]
  languageName = "Українська"
  weight = 11

[languages.zh-cn]
  languageName = "中文（简体）"
  weight = 12

[languages.tr]
  languageName = "Türkçe"
  weight = 13

[languages.ar]
  languageName = "عربى"
  weight = 14
