baseurl = "https://code.makery.ch"
title = "code.makery.ch"
pluralizeListTitles = false
preserveTaxonomyNames = true
removePathAccents = true
enableRobotsTXT = true

defaultContentLanguage = "en"

[params]
  intro = "Learning how to code."
  author = "Marco Jakob"
  email = "info@makery.ch"
  analyticsId = "UA-34917397-3"
  disqusShortname = "codemakery"
  googlePlus = "+MarcoJakob7"
  twitter = "codemakery"

[permalinks]
  blog-tag = "/blog/tag/:title/"

[Languages]
[Languages.en]
  title = "English"

[Languages.de]
  title = "Deutsch"

[Languages.es]
  title = "Español"

[Languages.fa]
  title = "فارسی"

[Languages.fr]
  title = "Français"

[Languages.id]
  title = "Bahasa Indonesia"

[Languages.it]
  title = "Italiano"

[Languages.kr]
  title = "한국어"

[Languages.pt]
  title = "Português"

[Languages.ru]
  title = "Русский"

[Languages.tr]
  title = "Türkçe"

[Languages.uk]
  title = "Українська"

[Languages.zh-cn]
  title = "中文（简体）"
